### ISSUE TITLE
Roll in Amendment on Revision

### ISSUE THREAD

**Issue by SteveLLamb** [SMPTE/st429-6#1]
Roll in ST 429-6:2006 Am1:2018 into ST 429-6:2006 with other changes

**Comment by jpviollet** [comment]
I see that ST429-6 Amendment 1:2018 is proposed to be included in ST429-6 revision.

The reason why this Amendment was explicitly forbidden for D-Cinema so far was not only because of the 2004 MXF specification usage, but also because the D-Cinema implementations were required to use the same “Encrypted Essence Container Label” value (per ST429-6:2006) regardless if the content is frame wrapped or clip wrapped - and the Amendment requires 2 different label values instead.

Using the Amendment 1:2018 labels has been confirmed in the past as being an issue on some D-Cinema equipment, and after double-checking, I confirm that the same issue still exist today.

Value used for D-Cinema should not change. If other applications like IMF are using the Amendment 2018 values, it is fine, it should just be made very clear that for D-Cinema applications, only  **060e2b34 04010107 0d010301 020b0100** shall be used in all cases. Thank you.

**Comment by palemieux** [comment]
@SteveLLamb Amendment rolled-up at https://doc.smpte-doc.org/st429-6-private/main/

**Comment by palemieux** [comment]
@jpviollet I suggest we solve the essence container label issue at #4

**Comment by jpviollet** [comment]
Ok to solve this issue at https://github.com/SMPTE/st429-6/issues/4, thank you Pierre.

**Comment by SteveLLamb** [comment]
Accepted on my end as well.
